#!/usr/bin/env python3
"""merge/writeups/*.json (the public halves) → merge/writeups.js, the module the site imports.

Only write-ups Kay marked approved in the Studio (status "approved", on the site) go in; every other project keeps its
panel copy from content.js. The module also carries the slice of the Studio library those write-ups use (templates,
floor names, software, classes) and their icon paths, plus the site copy (_site.json: cards, floors, all other text). The Studio server runs this after every save, build.py before bundling.

    python3 merge/writeups_export.py      → prints which write-ups are live
"""
import json, pathlib


def export(merge_dir):
    merge = pathlib.Path(merge_dir)
    pub = merge / 'writeups'
    lib = json.loads((pub / '_studio.json').read_text())
    icons = json.loads((merge / 'vendor' / 'tool-icons.json').read_text()).get('icons', {})
    live = {}
    for f in sorted(pub.glob('*.json')):
        if f.stem.startswith('_'): continue
        d = json.loads(f.read_text())
        if d.get('status') == 'approved' and d.get('onSite'):
            live[d.get('slug') or f.stem] = d
    used_sw = {s for d in live.values() for s in d.get('software', [])}
    used_cl = {c for d in live.values() for c in d.get('classes', [])}
    software = [s for s in lib.get('software', []) if s['id'] in used_sw]
    site_lib = {
        'templates': {k: t for k, t in lib.get('templates', {}).items() if any(d.get('template') == k for d in live.values())},
        'floors': [{k: f.get(k) for k in ('id', 'num', 'title')} for f in lib.get('floors', [])],
        'software': software,
        'classes': [c for c in lib.get('classes', []) if c['id'] in used_cl],
    }
    site_icons = {s['si']: {'path': icons[s['si']]['path']} for s in software if s.get('si') in icons}
    site_path = pub / '_site.json'
    site_text = json.loads(site_path.read_text()) if site_path.exists() else {}
    out = ('// Generated by merge/writeups_export.py from merge/writeups/*.json. Edit in the Studio, not here.\n'
           '// Only the write-ups Kay approved are in it; the other projects keep their panel copy in content.js.\n'
           f'export const WRITEUPS = {json.dumps(live, ensure_ascii=False)};\n'
           f'export const WRITEUP_LIB = {json.dumps(site_lib, ensure_ascii=False)};\n'
           f'export const TOOL_ICONS = {json.dumps(site_icons, ensure_ascii=False)};\n'
           f'export const SITE_TEXT = {json.dumps(site_text, ensure_ascii=False)};   // the site copy Kay edits in the Studio (Site text)\n')
    target = merge / 'writeups.js'
    if not target.exists() or target.read_text() != out:
        target.write_text(out)
    return sorted(live)


if __name__ == '__main__':
    print('live write-ups:', ', '.join(export(pathlib.Path(__file__).parent)) or 'none yet (approve one in the Studio)')
