// Generated by merge/writeups_export.py from merge/writeups/*.json. Edit in the Studio, not here.
// Only the write-ups Kay approved are in it; the other projects keep their panel copy in content.js.
export const WRITEUPS = {};
export const WRITEUP_LIB = {"templates": {}, "floors": [{"id": "engineering", "num": "01", "title": "ENGINEERING"}, {"id": "design", "num": "02", "title": "DESIGN & INTERACTION"}, {"id": "analytics", "num": "03", "title": "ANALYTICS & STRATEGY"}], "software": [], "classes": []};
export const TOOL_ICONS = {};
